- id: '1576525220015'
  alias: Turn off light when all are leaving home
  description: ''
  trigger:
  - entity_id: group.persons
    for: 0:15:00
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_off
- id: '1576702192277'
  alias: Turn on light when sun is set and someone is home
  description: ''
  trigger:
  - event: sunset
    offset: -00:60:00
    platform: sun
  condition:
  - condition: state
    entity_id: group.persons
    state: home
  action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_on
  - data:
      entity_id: scene.neutraal
    service: scene.turn_on
- id: '1576703543062'
  alias: Turn off toplevel heating late at night
  description: ''
  trigger:
  - at: '22:15'
    platform: time
  condition: []
  action:
  - data:
      entity_id: climate.zolder
      temperature: 11
    service: climate.set_temperature
- id: '1578604665837'
  alias: Turn on light when motion is detected and nobody is home
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.persons
    state: not_home
  - after: sunset
    after_offset: '-1:00:00'
    condition: sun
  action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_on
- id: '1578689101866'
  alias: Turn on light when somebody comes home
  description: ''
  trigger:
  - entity_id: group.persons
    from: not_home
    platform: state
    to: home
  condition:
  - after: sunset
    after_offset: '-1:00:00'
    condition: sun
  action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_on
- id: '1578690260667'
  alias: Turn on light early in the morning
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - before: sunrise
    condition: sun
  - condition: state
    entity_id: light.kitchen
    state: 'off'
  action:
  - data:
      entity_id: scene.neutraal
    service: scene.turn_on
- id: '1578690553061'
  alias: Turn cosy preset on
  description: ''
  trigger:
  - at: '19:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: light.kitchen
    state: 'on'
  action:
  - data:
      entity_id: scene.sfeervol
    service: scene.turn_on
- id: '1579297776451'
  alias: Notify when galileo is offline
  description: ''
  trigger:
  - payload: disconnected
    platform: mqtt
    topic: galileo/status
  condition: []
  action:
  - data:
      message: Intel Galileo disconnected
    service: notify.mobile_app_nokia_7_plus
