- id: '1576525220015'
  alias: Turn off light when all are leaving home
  description: ''
  trigger:
  - entity_id: group.persons
    for: 0:15:00
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_off
- id: '1576702192277'
  alias: Turn on light when sun is set and someone is home and it is getting dark
  description: ''
  trigger:
  - below: '55'
    entity_id: sensor.light_sensor
    platform: numeric_state
  condition:
  - condition: state
    entity_id: group.persons
    state: home
  action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_on
  - data:
      entity_id: scene.neutraal
    service: scene.turn_on
- id: '1576703543062'
  alias: Turn off toplevel heating late at night
  description: ''
  trigger:
  - at: '22:15'
    platform: time
  condition: []
  action:
  - data:
      entity_id: climate.zolder
      temperature: 11
    service: climate.set_temperature
- id: '1578604665837'
  alias: Turn on light when motion is detected, nobody is home, and it is dark
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.persons
    state: not_home
  - below: '55'
    condition: numeric_state
    entity_id: sensor.light_sensor
  action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_on
- id: '1578689101866'
  alias: Turn on light when somebody comes home and it is dark
  description: ''
  trigger:
  - entity_id: group.persons
    from: not_home
    platform: state
    to: home
  condition:
  - below: '25'
    condition: numeric_state
    entity_id: sensor.light_sensor
  action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_on
- id: '1578690260667'
  alias: Turn on light early in the morning
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - before: sunrise
    condition: sun
  - condition: state
    entity_id: light.kitchen
    state: 'off'
  - after: 05:00
    before: 09:00
    condition: time
  - below: '55'
    condition: numeric_state
    entity_id: sensor.light_sensor
  action:
  - data:
      entity_id: scene.vroeg_opstaan
    service: scene.turn_on
- id: '1578690553061'
  alias: Turn cosy preset on
  description: ''
  trigger:
  - at: '19:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: light.kitchen
    state: 'on'
  action:
  - data:
      entity_id: scene.sfeervol
    service: scene.turn_on
- id: '1579297776451'
  alias: Notify when galileo is offline
  description: ''
  trigger:
  - payload: disconnected
    platform: mqtt
    topic: galileo/status
  condition: []
  action:
  - data:
      message: Intel Galileo disconnected
    service: notify.mobile_app_nokia_7_plus
- id: '1584562019238'
  alias: Turn off light when it is not dark anymore
  description: ''
  trigger:
  - above: '70'
    entity_id: sensor.light_sensor
    platform: numeric_state
  condition: []
  action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_off
