- id: '1576523221744'
  alias: Turn on light when someone arrives home
  description: Only when nobody is at home
  trigger:
  - entity_id: group.persons
    from: not_home
    platform: state
    to: home
  condition:
  - after: sunset
    after_offset: -00:60:00
    condition: sun
  action:
  - alias: ''
    data:
      entity_id: group.lights
    service: homeassistant.turn_on
- id: '1576525220015'
  alias: Turn off light when all are leaving home
  description: ''
  trigger:
  - entity_id: group.persons
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_off
- id: '1576702192277'
  alias: Turn on light when sun is set and someone is home
  description: ''
  trigger:
  - event: sunset
    offset: -00:60:00
    platform: sun
  condition:
  - condition: state
    entity_id: group.persons
    state: home
  action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_on
  - data:
      entity_id: scene.neutraal
    service: scene.turn_on
- id: '1576703543062'
  alias: Turn off toplevel heating late at night
  description: ''
  trigger:
  - at: '22:15'
    platform: time
  condition: []
  action:
  - data:
      entity_id: climate.zolder
      temperature: 11
    service: climate.set_temperature
- id: '1578604665837'
  alias: Motion detected - Nobody at home
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.persons
      state: not_home
    - condition: sun
      after: sunset
      after_offset: -00:60:00
      
  action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_on
