- id: '1576525220015'
  alias: Turn off light when all are leaving home
  description: ''
  trigger:
  - entity_id: group.persons
    for: 0:15:00
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_off
- id: '1576702192277'
  alias: Turn on light when someone is home and it is getting dark
  description: ''
  trigger:
  - below: '50'
    entity_id: sensor.light_sensor
    for: 0:10:00
    platform: numeric_state
  condition:
  - condition: state
    entity_id: group.persons
    state: home
  - condition: state
    entity_id: light.kitchen
    state: 'off'
  action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_on
  - data:
      entity_id: scene.neutraal
    service: scene.turn_on
  mode: single
- id: '1576703543062'
  alias: Turn off toplevel heating late at night
  description: ''
  trigger:
  - at: '22:15'
    platform: time
  condition: []
  action:
  - data:
      entity_id: climate.zolder
      temperature: 11
    service: climate.set_temperature
- id: '1578604665837'
  alias: Turn on light when motion is detected, nobody is home, and it is dark
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.persons
    state: not_home
  - below: '50'
    condition: numeric_state
    entity_id: sensor.light_sensor
  action:
  - scene: scene.neutraal
- id: '1578689101866'
  alias: Turn on light when somebody comes home and it is dark
  description: ''
  trigger:
  - entity_id: group.persons
    from: not_home
    platform: state
    to: home
  condition:
  - below: '50'
    condition: numeric_state
    entity_id: sensor.light_sensor
  action:
  - scene: scene.neutraal
- id: '1578690260667'
  alias: Turn on light early in the morning
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.kitchen
    state: 'off'
  - after: 06:20
    before: 09:00
    condition: time
  - below: '50'
    condition: numeric_state
    entity_id: sensor.light_sensor
  action:
  - data:
      entity_id: scene.neutraal
    service: scene.turn_on
  mode: single
- id: '1578690553061'
  alias: Turn cosy preset on
  description: ''
  trigger:
  - below: '30'
    entity_id: sensor.light_sensor
    platform: numeric_state
  condition:
  - condition: state
    entity_id: light.kitchen
    state: 'on'
  - after: '19:00:00'
    condition: time
  - after: sunset
    condition: sun
  - condition: state
    entity_id: light.couch
    state: 'off'
  action:
  - data:
      entity_id: scene.sfeervol
    service: scene.turn_on
  mode: single
- id: '1584562019238'
  alias: Turn off light when it is not dark anymore
  description: ''
  trigger:
  - above: '65'
    entity_id: sensor.light_sensor
    for: 0:05:00
    platform: numeric_state
  condition: []
  action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_off
- id: '1585490618536'
  alias: Turn on light in the middle of the night
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - below: '50'
    condition: numeric_state
    entity_id: sensor.light
  - after: 00:01
    before: 05:00
    condition: time
  action:
  - alias: ''
    data:
      entity_id: scene.vroeg
    service: scene.turn_on
- id: '1585490882099'
  alias: Turn off light in the middle of the night
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_sensor
    for: 0:15:00
    platform: state
    to: 'off'
  condition:
  - after: 00:01
    before: 05:30
    condition: time
  action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_off
- id: '1591217821080'
  alias: 'Holiday: Lights on'
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - scene: scene.sfeervol
- id: '1591218045607'
  alias: 'Holiday: Lights off'
  description: ''
  trigger:
  - at: '23:30'
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_off
- id: '1594736266674'
  alias: Reset Galileo on disconnect
  description: ''
  trigger:
  - payload: disconnected
    platform: mqtt
    topic: galileo/status
  condition: []
  action:
  - device_id: 8b2aebff03c542828a689ff42f651c60
    domain: switch
    entity_id: switch.bf6361796461abc8b0rsyx
    type: turn_off
  - delay: 00:01:00
  - device_id: 8b2aebff03c542828a689ff42f651c60
    domain: switch
    entity_id: switch.bf6361796461abc8b0rsyx
    type: turn_on
