default_config:

mobile_app:

http:
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  base_url: !secret baseurl

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
device_tracker: !include device_tracker.yaml

homeassistant:
  customize: !include customize.yaml
  customize_domain:
    light:
      assumed_state: false

mqtt:
  broker: farmer.cloudmqtt.com
  port: 11245
  username: !secret mqtt_usr
  password: !secret mqtt_pwd

tplink:
  discovery: false
  switch:
    - host: 192.168.1.10
    - host: 192.168.1.24
    - host: 192.168.1.25

light:
  platform: limitlessled
  bridges:
    - host: 192.168.1.15
      groups:
      - number: 1
        type: rgbww
        name: Kitchen

group:
  Lights:
    entities:
      - switch.tp1
      - switch.tp2
      - light.kitchen    
  Persons:
    entities:
      - device_tracker.peter_ping
      - device_tracker.willeke_ping

evohome:
  username: !secret evohome_usr
  password: !secret evohome_pwd

binary_sensor:
  - platform: ping
    host: 192.168.1.17
  - platform: mqtt
    name: "Motion Sensor"
    state_topic: "sensor/motion"
    payload_on: "ON"
    off_delay: 10

sensor:
  - platform: mqtt
    name: "P1 Sensor (El. C)"
    state_topic: "sensor/p1"
    unit_of_measurement: 'W'
    value_template: "{{ value_json.electricity_actual_received * 1000 }}"
  - platform: mqtt
    name: "P1 Sensor (El. T1)"
    state_topic: "sensor/p1"
    unit_of_measurement: 'kWh'
    value_template: "{{ value_json.electricity_tariff1_received }}"
  - platform: mqtt
    name: "P1 Sensor (El. T2)"
    state_topic: "sensor/p1"
    unit_of_measurement: 'kWh'
    value_template: "{{ value_json.electricity_tariff2_received }}"
  - platform: mqtt
    name: "P1 Sensor (Gas T)"
    state_topic: "sensor/p1"
    unit_of_measurement: 'm3'
    value_template: "{{ value_json.gas_received }}"
  - platform: template
    sensors:
      tp1_amps:
        friendly_name_template: "{{ states.switch.tp1.name}} Current"
        value_template: '{{ states.switch.tp1.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      tp1_watts:
        friendly_name_template: "{{ states.switch.tp1.name}} Current Consumption"
        value_template: '{{ states.switch.tp1.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      tp1_total_kwh:
        friendly_name_template: "{{ states.switch.tp1.name}} Total Consumption"
        value_template: '{{ states.switch.tp1.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      tp1_volts:
        friendly_name_template: "{{ states.switch.tp1.name}} Voltage"
        value_template: '{{ states.switch.tp1.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
      tp1_today_kwh:
        friendly_name_template: "{{ states.switch.tp1.name}} Today's Consumption"
        value_template: '{{ states.switch.tp1.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'  
      tp2_amps:
        friendly_name_template: "{{ states.switch.tp2.name}} Current"
        value_template: '{{ states.switch.tp2.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      tp2_watts:
        friendly_name_template: "{{ states.switch.tp2.name}} Current Consumption"
        value_template: '{{ states.switch.tp2.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      tp2_total_kwh:
        friendly_name_template: "{{ states.switch.tp2.name}} Total Consumption"
        value_template: '{{ states.switch.tp2.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      tp2_volts:
        friendly_name_template: "{{ states.switch.tp2.name}} Voltage"
        value_template: '{{ states.switch.tp2.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
      tp2_today_kwh:
        friendly_name_template: "{{ states.switch.tp2.name}} Today's Consumption"
        value_template: '{{ states.switch.tp2.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'    
      tp3_amps:
        friendly_name_template: "{{ states.switch.tp3.name}} Current"
        value_template: '{{ states.switch.tp3.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      tp3_watts:
        friendly_name_template: "{{ states.switch.tp3.name}} Current Consumption"
        value_template: '{{ states.switch.tp3.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      tp3_total_kwh:
        friendly_name_template: "{{ states.switch.tp3.name}} Total Consumption"
        value_template: '{{ states.switch.tp3.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      tp3_volts:
        friendly_name_template: "{{ states.switch.tp3.name}} Voltage"
        value_template: '{{ states.switch.tp3.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
      tp3_today_kwh:
        friendly_name_template: "{{ states.switch.tp3.name}} Today's Consumption"
        value_template: '{{ states.switch.tp3.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'                  

google_assistant:
  project_id: home-automation-8e76d
  service_account: !include Home Automation-4dc884a9c90c.json
  report_state: true
  exposed_domains:
    - switch
    - light
    - scene

history:
  exclude:
    domains:
      - device_tracker
      - automation
      - person
    entities:
      - binary_sensor.updater
      - group.all_automations
      - group.all_lights
      - group.all_switches
      - group.all_devices

logbook:
  exclude:
    entities:
      - binary_sensor.motion_sensor      